version: '2.1'
services:
  kali:
    build:
      context: ./kali
      dockerfile: kali.df
    command: tail -f 2>&1 /dev/null
    privileged: true
    container_name: Kali

  target:
    build:
      context: ./target
      dockerfile: target.df
    command: tail -f 2>&1 /dev/null
    privileged: true 
    container_name: Target
